CanFestival: Node-guarding Object
Node-guarding Object
Communication Objects
Functions
void nodeguardInit (CO_Data *d)
Start node guarding with respect to 0x100C and 0x100D in the object dictionary.
void nodeguardStop (CO_Data *d)
Stop producing node guarding messages.
void proceedNODE_GUARD (CO_Data *d, Message *m)
This function is responsible to process a canopen-message which seams to be an NMT Error Control Messages. If a BootUp message is detected, it will return the nodeId of the Slave who booted up.
void GuardTimeAlarm (CO_Data *d, UNS32 id)
The guardTime - Timer Callback.
UNS32 OnNodeGuardUpdate (CO_Data *d, const indextable *unused_indextable, UNS8 unused_bSubindex)
Detailed Description
The node-guarding mechanism for a device is established through cyclically polling all slaves by the NMT master. If one polled slave does not respond during a specified time (LifeTime), the local application will be informed about that event.
It is also possible for the slaves to monitor the node-guarding requests coming from the master to determine, if the master operates in a right way
Todo:
The implementation is very basic. The toggle bit of the nodes confirmation is not checked at the moment
Function Documentation
void GuardTimeAlarm (CO_Data * d, UNS32 id)
The guardTime - Timer Callback.
This function is called every GuardTime (OD 0x100C) ms
On every call, a NodeGuard-Request is sent to all nodes which have a node-state not equal to "Unknown" (according to NMTable). If the node has not responded within the lifetime, the nodeguardError function is called and the status of this node is set to "Disconnected"
Parameters
d Pointer on a CAN object data structure
id
Send node guard request to all nodes except this node, if the node state is not "Unknown_state"
Check if the node has confirmed the guarding request within the LifeTime (GuardTime x LifeTimeFactor)
Definition at line 210 of file lifegrd.c.
References DelAlarm(), and masterSendNMTnodeguard().
Referenced by nodeguardInit().
void nodeguardInit (CO_Data * d)
Start node guarding with respect to 0x100C and 0x100D in the object dictionary.
Parameters
*d Pointer on a CAN object data structure
Set initial value for the nodes
Definition at line 313 of file lifegrd.c.
References GuardTimeAlarm(), OnNodeGuardUpdate(), and SetAlarm().
Referenced by lifeGuardInit(), and OnNodeGuardUpdate().
void nodeguardStop (CO_Data * d)
Stop producing node guarding messages.
Parameters
*d Pointer on a CAN object data structure
Definition at line 349 of file lifegrd.c.
References DelAlarm().
Referenced by lifeGuardStop(), and OnNodeGuardUpdate().
UNS32 OnNodeGuardUpdate (CO_Data * d, const indextable * unused_indextable, UNS8 unused_bSubindex)
This function is called, if index 0x100C or 0x100D is updated to restart the node-guarding service with the new parameters
Parameters
d Pointer on a CAN object data structure
unused_indextable
unused_bSubindex
Definition at line 263 of file lifegrd.c.
References nodeguardInit(), and nodeguardStop().
Referenced by nodeguardInit().
void proceedNODE_GUARD (CO_Data * d, Message * m)
This function is responsible to process a canopen-message which seams to be an NMT Error Control Messages. If a BootUp message is detected, it will return the nodeId of the Slave who booted up.
Parameters
*d Pointer on a CAN object data structure
*m Pointer on the CAN-message which has to be analysed.
Notice that only the master can have sent this node guarding request
Receiving a NMT NodeGuarding (request of the state by the master) Only answer to the NMT NodeGuarding request, the master is not checked (not implemented)
Record node response for node guarding service
Definition at line 82 of file lifegrd.c.
References Message::cob_id, ConsumerHeartbeatAlarm(), Message::data, DelAlarm(), Message::len, Message::rtr, and SetAlarm().
Referenced by canDispatch().