CanFestival: Timer Management
Timer Management
User API
Functions
TIMER_HANDLE SetAlarm (CO_Data *d, UNS32 id, TimerCallback_t callback, TIMEVAL value, TIMEVAL period)
Set an alarm to execute a callback function when expired.
TIMER_HANDLE DelAlarm (TIMER_HANDLE handle)
Delete an alarm before expiring.
void setTimer (TIMEVAL value)
Set a timerfor a given time.
TIMEVAL getElapsedTime (void)
Get the time elapsed since latest timer occurence.
void EnterMutex (void)
Acquire mutex.
void LeaveMutex (void)
Release mutex.
void TimerInit (void)
Initialize Timer.
void TimerCleanup (void)
Cleanup Timer.
void StartTimerLoop (TimerCallback_t Callback)
Start the timer task.
void StopTimerLoop (TimerCallback_t Callback)
Stop the timer task.
Detailed Description
Function Documentation
TIMER_HANDLE DelAlarm (TIMER_HANDLE handle)
Delete an alarm before expiring.
Parameters
handle A timer handle
Returns
The timer handle
--— Use this to remove an alarm -—
Parameters
handle
Returns
Definition at line 103 of file timer.c.
Referenced by GuardTimeAlarm(), heartbeatStop(), nodeguardStop(), PDOStop(), proceedNODE_GUARD(), proceedPDO(), ProducerHeartbeatAlarm(), stopSYNC(), and TPDO_Communication_Parameter_Callback().
TIMEVAL getElapsedTime (void)
Get the time elapsed since latest timer occurence.
Returns
time elapsed since latest timer occurence
Definition at line 160 of file timers_unix.c.
Referenced by SetAlarm().
TIMER_HANDLE SetAlarm (CO_Data * d, UNS32 id, TimerCallback_t callback, TIMEVAL value, TIMEVAL period)
Set an alarm to execute a callback function when expired.
Parameters
*d Pointer to a CAN object data structure
id The alarm Id
callback A callback function
value Call the callback function at current time + value
period Call periodically the callback function
Returns
handle The timer handle
----— Use this to declare a new alarm ---—
Parameters
d
id
callback
value
period
Returns
Definition at line 57 of file timer.c.
References getElapsedTime(), and setTimer().
Referenced by heartbeatInit(), nodeguardInit(), proceedNODE_GUARD(), proceedPDO(), startSYNC(), and StartTimerLoop().
void setTimer (TIMEVAL value)
Set a timerfor a given time.
Parameters
value The time value.
Definition at line 145 of file timers_unix.c.
Referenced by SetAlarm().
void StartTimerLoop (TimerCallback_t Callback)
Start the timer task.
Parameters
Callback A callback function
Definition at line 83 of file timers_unix.c.
References EnterMutex(), LeaveMutex(), and SetAlarm().
void StopTimerLoop (TimerCallback_t Callback)
Stop the timer task.
Parameters
Callback A callback function
Definition at line 73 of file timers_unix.c.
References EnterMutex(), and LeaveMutex().