CanFestival: src/lifegrd.c File Reference
lifegrd.c File Reference
#include <data.h>
#include "lifegrd.h"
#include "canfestival.h"
#include "dcf.h"
#include "sysdep.h"
Functions
void ConsumerHeartbeatAlarm (CO_Data *d, UNS32 id)
void ProducerHeartbeatAlarm (CO_Data *d, UNS32 id)
void GuardTimeAlarm (CO_Data *d, UNS32 id)
The guardTime - Timer Callback.
UNS32 OnNodeGuardUpdate (CO_Data *d, const indextable *unused_indextable, UNS8 unused_bSubindex)
e_nodeState getNodeState (CO_Data *d, UNS8 nodeId)
To read the state of a node This can be used by the master after having sent a life guard request, of by any node if it is waiting for heartbeat.
void proceedNODE_GUARD (CO_Data *d, Message *m)
This function is responsible to process a canopen-message which seams to be an NMT Error Control Messages. If a BootUp message is detected, it will return the nodeId of the Slave who booted up.
UNS32 OnHeartbeatProducerUpdate (CO_Data *d, const indextable *unused_indextable, UNS8 unused_bSubindex)
void heartbeatInit (CO_Data *d)
Start heartbeat consumer and producer with respect to 0x1016 and 0x1017 object dictionary entries.
void nodeguardInit (CO_Data *d)
Start node guarding with respect to 0x100C and 0x100D in the object dictionary.
void heartbeatStop (CO_Data *d)
Stop heartbeat consumer and producer.
void nodeguardStop (CO_Data *d)
Stop producing node guarding messages.
void lifeGuardInit (CO_Data *d)
Start the life guarding service (heartbeat/node guarding). This service handles NMT error control messages either by using heartbeats and/or by using node guarding messages (defined via the object dictionary)
void lifeGuardStop (CO_Data *d)
Stop the life guarding service (heartbeat/node guarding).
Detailed Description
Author
Edouard TISSERANT
Date
Mon Jun 4 17:19:24 2007
Definition in file lifegrd.c.
Function Documentation
void lifeGuardInit (CO_Data * d)
Start the life guarding service (heartbeat/node guarding). This service handles NMT error control messages either by using heartbeats and/or by using node guarding messages (defined via the object dictionary)
Parameters
*d Pointer on a CAN object data structure
Definition at line 355 of file lifegrd.c.
References heartbeatInit(), and nodeguardInit().
Referenced by switchCommunicationState().
void lifeGuardStop (CO_Data * d)
Stop the life guarding service (heartbeat/node guarding).
Parameters
*d Pointer on a CAN object data structure
Definition at line 362 of file lifegrd.c.
References heartbeatStop(), and nodeguardStop().
Referenced by switchCommunicationState().