CanFestival: src/sdo.c File Reference
sdo.c File Reference
#include <stdlib.h>
#include "canfestival.h"
#include "sysdep.h"
Macros
#define getSDOcs(byte) (byte >> 5)
#define getSDOn2(byte) ((byte >> 2) & 3)
#define getSDOn3(byte) ((byte >> 1) & 7)
#define getSDOe(byte) ((byte >> 1) & 1)
#define getSDOs(byte) (byte & 1)
#define getSDOc(byte) (byte & 1)
#define getSDOt(byte) ((byte >> 4) & 1)
#define getSDOindex(byte1, byte2) (((UNS16)byte2 << 8) | ((UNS16)byte1))
#define getSDOsubIndex(byte3) (byte3)
#define getSDOblockSC(byte) (byte & 3)
Functions
UNS8 GetSDOClientFromNodeId (CO_Data *d, UNS8 nodeId)
INLINE UNS8 _writeNetworkDict (CO_Data *d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS32 count, UNS8 dataType, void *data, SDOCallback_t Callback, UNS8 endianize, UNS8 useBlockMode)
INLINE UNS8 _readNetworkDict (CO_Data *d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS8 dataType, SDOCallback_t Callback, UNS8 useBlockMode)
void SDOTimeoutAlarm (CO_Data *d, UNS32 id)
Reset of a SDO exchange on timeout. Send a SDO abort.
void resetSDO (CO_Data *d)
Reset all SDO buffers.
UNS32 SDOlineToObjdict (CO_Data *d, UNS8 line)
Copy the data received from the SDO line transfer to the object dictionary.
UNS32 objdictToSDOline (CO_Data *d, UNS8 line)
Copy the data from the object dictionary to the SDO line for a network transfer.
UNS8 lineToSDO (CO_Data *d, UNS8 line, UNS32 nbBytes, UNS8 *data)
Copy data from an existant line in the argument "* data".
UNS8 SDOtoLine (CO_Data *d, UNS8 line, UNS32 nbBytes, UNS8 *data)
Add data to an existant line.
UNS8 failedSDO (CO_Data *d, UNS8 CliServNbr, UNS8 whoami, UNS16 index, UNS8 subIndex, UNS32 abortCode)
Called when an internal SDO abort occurs. Release the line * Only if server * If client, the line must be released manually in the core application. The reason of that is to permit the program to read the transfers structure before its reset, because many informations are stored on it : index, subindex, data received or trasmited, ... In all cases, sends a SDO abort.
void resetSDOline (CO_Data *d, UNS8 line)
Reset an unused line.
UNS8 initSDOline (CO_Data *d, UNS8 line, UNS8 CliServNbr, UNS16 index, UNS8 subIndex, UNS8 state)
Initialize some fields of the structure.
UNS8 getSDOfreeLine (CO_Data *d, UNS8 whoami, UNS8 *line)
Search for an unused line in the transfers array to store a new SDO. ie a line which value of the field "state" is "SDO_RESET" An unused line have the field "state" at the value SDO_RESET.
UNS8 getSDOlineOnUse (CO_Data *d, UNS8 CliServNbr, UNS8 whoami, UNS8 *line)
Search for the line, in the transfers array, which contains the beginning of the reception of a fragmented SDO.
UNS8 getSDOlineToClose (CO_Data *d, UNS8 CliServNbr, UNS8 whoami, UNS8 *line)
Search for the line, in the transfers array, which contains the beginning of the reception of a fragmented SDO.
UNS8 closeSDOtransfer (CO_Data *d, UNS8 nodeId, UNS8 whoami)
Close a transmission.
UNS8 getSDOlineRestBytes (CO_Data *d, UNS8 line, UNS32 *nbBytes)
Bytes in the line structure which must be transmited (or received)
UNS8 setSDOlineRestBytes (CO_Data *d, UNS8 line, UNS32 nbBytes)
Store in the line structure the nb of bytes which must be transmited (or received)
UNS8 sendSDO (CO_Data *d, UNS8 whoami, UNS8 CliServNbr, UNS8 *pData)
Transmit a SDO frame on the bus bus_id.
UNS8 sendSDOabort (CO_Data *d, UNS8 whoami, UNS8 CliServNbr, UNS16 index, UNS8 subIndex, UNS32 abortCode)
Transmit a SDO error to the client. The reasons may be : Read/Write to a undefined object Read/Write to a undefined subindex Read/write a not valid length object Write a read only object.
UNS8 proceedSDO (CO_Data *d, Message *m)
Treat a SDO frame reception call the function sendSDO.
UNS8 writeNetworkDict (CO_Data *d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS32 count, UNS8 dataType, void *data, UNS8 useBlockMode)
Used to send a SDO request frame to write the data at the index and subIndex indicated.
UNS8 writeNetworkDictCallBack (CO_Data *d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS32 count, UNS8 dataType, void *data, SDOCallback_t Callback, UNS8 useBlockMode)
Used to send a SDO request frame to write in a distant node dictionnary.
UNS8 writeNetworkDictCallBackAI (CO_Data *d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS32 count, UNS8 dataType, void *data, SDOCallback_t Callback, UNS8 endianize, UNS8 useBlockMode)
Used to send a SDO request frame to write in a distant node dictionnary.
UNS8 readNetworkDict (CO_Data *d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS8 dataType, UNS8 useBlockMode)
Used to send a SDO request frame to read.
UNS8 readNetworkDictCallback (CO_Data *d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS8 dataType, SDOCallback_t Callback, UNS8 useBlockMode)
Used to send a SDO request frame to read in a distant node dictionnary.
UNS8 readNetworkDictCallbackAI (CO_Data *d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS8 dataType, SDOCallback_t Callback, UNS8 useBlockMode)
Used to send a SDO request frame to read in a distant node dictionnary.
UNS8 getReadResultNetworkDict (CO_Data *d, UNS8 nodeId, void *data, UNS32 *size, UNS32 *abortCode)
Use this function after calling readNetworkDict to get the result.
UNS8 getWriteResultNetworkDict (CO_Data *d, UNS8 nodeId, UNS32 *abortCode)
Use this function after calling writeNetworkDict function to get the result of the write.
Detailed Description
Author
Edouard TISSERANT and Francis DUPIN
Date
Tue Jun 5 09:32:32 2007
Definition in file sdo.c.
Macro Definition Documentation
#define getSDOblockSC (byte) (byte & 3)
Returns the subcommand in SDO block transfer
Definition at line 128 of file sdo.c.
Referenced by proceedSDO().
#define getSDOc (byte) (byte & 1)
Returns the indicator of end transmission from the first byte of the SDO
Definition at line 112 of file sdo.c.
Referenced by proceedSDO().
#define getSDOcs (byte) (byte >> 5)
Returns the command specifier (cs, ccs, scs) from the first byte of the SDO
Definition at line 92 of file sdo.c.
Referenced by proceedSDO().
#define getSDOe (byte) ((byte >> 1) & 1)
Returns the transfer type from the first byte of the SDO
Definition at line 104 of file sdo.c.
Referenced by proceedSDO().
#define getSDOindex (byte1, byte2) (((UNS16)byte2 << 8) | ((UNS16)byte1))
Returns the index from the bytes 1 and 2 of the SDO
Definition at line 120 of file sdo.c.
Referenced by proceedSDO().
#define getSDOn2 (byte) ((byte >> 2) & 3)
Returns the number of bytes without data from the first byte of the SDO. Coded in 2 bits
Definition at line 96 of file sdo.c.
Referenced by proceedSDO().
#define getSDOn3 (byte) ((byte >> 1) & 7)
Returns the number of bytes without data from the first byte of the SDO. Coded in 3 bits
Definition at line 100 of file sdo.c.
Referenced by proceedSDO().
#define getSDOs (byte) (byte & 1)
Returns the size indicator from the first byte of the SDO
Definition at line 108 of file sdo.c.
Referenced by proceedSDO().
#define getSDOsubIndex (byte3) (byte3)
Returns the subIndex from the byte 3 of the SDO
Definition at line 124 of file sdo.c.
Referenced by proceedSDO().
#define getSDOt (byte) ((byte >> 4) & 1)
Returns the toggle from the first byte of the SDO
Definition at line 116 of file sdo.c.
Referenced by proceedSDO().
Function Documentation
INLINE UNS8 _readNetworkDict (CO_Data * d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS8 dataType, SDOCallback_t Callback, UNS8 useBlockMode)
Called by readNetworkDict
Parameters
d
nodeId
index
subIndex
dataType
Callback
Returns
Parameters
d
nodeId
index
subIndex
dataType
Callback
useBlockMode
Returns
Definition at line 2088 of file sdo.c.
References GetSDOClientFromNodeId(), getSDOfreeLine(), getSDOlineOnUse(), initSDOline(), resetSDOline(), and sendSDO().
Referenced by readNetworkDict(), readNetworkDictCallback(), and readNetworkDictCallbackAI().
INLINE UNS8 _writeNetworkDict (CO_Data * d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS32 count, UNS8 dataType, void * data, SDOCallback_t Callback, UNS8 endianize, UNS8 useBlockMode)
Called by writeNetworkDict
Parameters
d
nodeId
index
subIndex
count
dataType
data
Callback
endianize
Returns
Parameters
d
nodeId
index
subIndex
count
dataType
data
Callback
endianize
Returns
Normal transfer
Definition at line 1868 of file sdo.c.
References GetSDOClientFromNodeId(), getSDOfreeLine(), getSDOlineOnUse(), initSDOline(), resetSDOline(), and sendSDO().
Referenced by writeNetworkDict(), writeNetworkDictCallBack(), and writeNetworkDictCallBackAI().
UNS8 closeSDOtransfer (CO_Data * d, UNS8 nodeId, UNS8 whoami)
Close a transmission.
Parameters
d
CliServNbr
whoami
Returns
Definition at line 593 of file sdo.c.
References GetSDOClientFromNodeId(), getSDOlineToClose(), and resetSDOline().
UNS8 failedSDO (CO_Data * d, UNS8 CliServNbr, UNS8 whoami, UNS16 index, UNS8 subIndex, UNS32 abortCode)
Called when an internal SDO abort occurs. Release the line * Only if server * If client, the line must be released manually in the core application. The reason of that is to permit the program to read the transfers structure before its reset, because many informations are stored on it : index, subindex, data received or trasmited, ... In all cases, sends a SDO abort.
Parameters
d
CliServNbr
whoami
index
subIndex
abortCode
Returns
Definition at line 416 of file sdo.c.
References getSDOlineOnUse(), resetSDOline(), and sendSDOabort().
Referenced by proceedSDO().
UNS8 GetSDOClientFromNodeId (CO_Data * d, UNS8 nodeId)
Parameters
d
nodeId
Returns
0xFF : No SDO client available 0xFE : Not found otherwise : SDO client number
Definition at line 1811 of file sdo.c.
Referenced by _readNetworkDict(), _writeNetworkDict(), closeSDOtransfer(), getReadResultNetworkDict(), and getWriteResultNetworkDict().
UNS8 getSDOfreeLine (CO_Data * d, UNS8 whoami, UNS8 * line)
Search for an unused line in the transfers array to store a new SDO. ie a line which value of the field "state" is "SDO_RESET" An unused line have the field "state" at the value SDO_RESET.
Parameters
d
whoami
line
Returns
Definition at line 514 of file sdo.c.
Referenced by _readNetworkDict(), _writeNetworkDict(), and proceedSDO().
UNS8 getSDOlineOnUse (CO_Data * d, UNS8 CliServNbr, UNS8 whoami, UNS8 * line)
Search for the line, in the transfers array, which contains the beginning of the reception of a fragmented SDO.
Parameters
d
CliServNbr
whoami
line
Returns
Definition at line 540 of file sdo.c.
Referenced by _readNetworkDict(), _writeNetworkDict(), failedSDO(), getReadResultNetworkDict(), getWriteResultNetworkDict(), and proceedSDO().
UNS8 getSDOlineRestBytes (CO_Data * d, UNS8 line, UNS32 * nbBytes)
Bytes in the line structure which must be transmited (or received)
Parameters
d
line
nbBytes
Returns
Definition at line 620 of file sdo.c.
Referenced by proceedSDO().
UNS8 getSDOlineToClose (CO_Data * d, UNS8 CliServNbr, UNS8 whoami, UNS8 * line)
Search for the line, in the transfers array, which contains the beginning of the reception of a fragmented SDO.
Parameters
d
CliServNbr
whoami
line
Returns
Definition at line 567 of file sdo.c.
Referenced by closeSDOtransfer().
UNS8 initSDOline (CO_Data * d, UNS8 line, UNS8 CliServNbr, UNS16 index, UNS8 subIndex, UNS8 state)
Initialize some fields of the structure.
Parameters
d
line
CliServNbr
index
subIndex
state
Returns
Definition at line 471 of file sdo.c.
Referenced by _readNetworkDict(), _writeNetworkDict(), proceedSDO(), and resetSDOline().
UNS8 lineToSDO (CO_Data * d, UNS8 line, UNS32 nbBytes, UNS8 * data)
Copy data from an existant line in the argument "* data".
Parameters
d
line
nbBytes
data
Returns
Definition at line 302 of file sdo.c.
Referenced by proceedSDO().
UNS32 objdictToSDOline (CO_Data * d, UNS8 line)
Copy the data from the object dictionary to the SDO line for a network transfer.
Parameters
d
line
Returns
Definition at line 244 of file sdo.c.
References getODentry.
Referenced by proceedSDO().
UNS8 proceedSDO (CO_Data * d, Message * m)
Treat a SDO frame reception call the function sendSDO.
Parameters
d
m
Returns
Definition at line 745 of file sdo.c.
References Message::cob_id, Message::data, failedSDO(), getSDOblockSC, getSDOc, getSDOcs, getSDOe, getSDOfreeLine(), getSDOindex, getSDOlineOnUse(), getSDOlineRestBytes(), getSDOn2, getSDOn3, getSDOs, getSDOsubIndex, getSDOt, initSDOline(), lineToSDO(), objdictToSDOline(), resetSDOline(), SDOlineToObjdict(), SDOtoLine(), sendSDO(), and setSDOlineRestBytes().
Referenced by canDispatch().
void resetSDO (CO_Data * d)
Reset all SDO buffers.
Reset all sdo buffers
Parameters
d
Definition at line 186 of file sdo.c.
References resetSDOline().
Referenced by switchCommunicationState().
void resetSDOline (CO_Data * d, UNS8 line)
Reset an unused line.
Parameters
d
line
Definition at line 448 of file sdo.c.
References initSDOline().
Referenced by _readNetworkDict(), _writeNetworkDict(), closeSDOtransfer(), failedSDO(), getReadResultNetworkDict(), getWriteResultNetworkDict(), proceedSDO(), resetSDO(), and SDOTimeoutAlarm().
UNS32 SDOlineToObjdict (CO_Data * d, UNS8 line)
Copy the data received from the SDO line transfer to the object dictionary.
Parameters
d
line
Returns
Definition at line 203 of file sdo.c.
References setODentry.
Referenced by proceedSDO().
void SDOTimeoutAlarm (CO_Data * d, UNS32 id)
Reset of a SDO exchange on timeout. Send a SDO abort.
Parameters
d
id
Definition at line 137 of file sdo.c.
References resetSDOline(), and sendSDOabort().
UNS8 SDOtoLine (CO_Data * d, UNS8 line, UNS32 nbBytes, UNS8 * data)
Add data to an existant line.
Parameters
d
line
nbBytes
data
Returns
Definition at line 352 of file sdo.c.
Referenced by proceedSDO().
UNS8 sendSDO (CO_Data * d, UNS8 whoami, UNS8 CliServNbr, UNS8 * pData)
Transmit a SDO frame on the bus bus_id.
Parameters
d
whoami
CliServNbr
pData
Returns
Definition at line 662 of file sdo.c.
References Message::cob_id, Message::data, Message::len, and Message::rtr.
Referenced by _readNetworkDict(), _writeNetworkDict(), proceedSDO(), and sendSDOabort().
UNS8 sendSDOabort (CO_Data * d, UNS8 whoami, UNS8 CliServNbr, UNS16 index, UNS8 subIndex, UNS32 abortCode)
Transmit a SDO error to the client. The reasons may be : Read/Write to a undefined object Read/Write to a undefined subindex Read/write a not valid length object Write a read only object.
Parameters
d
whoami
index
subIndex
abortCode
Returns
Definition at line 715 of file sdo.c.
References sendSDO().
Referenced by failedSDO(), and SDOTimeoutAlarm().
UNS8 setSDOlineRestBytes (CO_Data * d, UNS8 line, UNS32 nbBytes)
Store in the line structure the nb of bytes which must be transmited (or received)
Parameters
d
line
nbBytes
Returns
Definition at line 639 of file sdo.c.
Referenced by proceedSDO().